### ISSUE TITLE
 Unable to resolve module `crypto`

### ISSUE THREAD

**Issue by lacvapps** [Airbitz/airbitz-core-js#47]
On a fresh edge-login install to react native, when I run react-native run-ios it will build successfully but when attempting to use the app it gives me the error.

> bundling failed: UnableToResolveError: Unable to resolve module `crypto` from `../node_modules/edge-login/lib/edge-core-index.js`: Module does not exist in the module map

**Comment by lacvapps** [comment]
running `npm install crypto` fixes the issue and now I have 

> bundling failed: Error: EISDIR: illegal operation on a directory, read at Object.fs.readSync

**Comment by lacvapps** [comment]
This is what the nom package `crypto` says in the readme

> # Deprecated Package
> 
> This package is no longer supported and has been deprecated. To avoid malicious use, npm is hanging on to the package name.
> 
> It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
> 
> Please contact support@npmjs.com if you have questions about this package.

**Comment by lacvapps** [comment]
Was able to get past this error by following 
https://github.com/tradle/react-native-crypto

**Comment by swansontec** [comment]
Aha, I see the problem. Our `edge-login` package needs to be hacked using `rn-nodeify --hack`. I'm not sure how that `crypto` dependency snuck its way in there, but using rn-nodeify successfully eliminates the problem (https://github.com/tradle/rn-nodeify). I think the proper solution is to fix the `edge-login` library to not require `crypto` on React Native, since we don't use it internally anywhere.

**Comment by swansontec** [comment]
I have created an issue in our internal bug tracker to get this resolved.

**Comment by lacvapps** [comment]
Okay sounds good, thank you for the fast reply!

**Comment by swansontec** [comment]
This should be fixed in v0.5.6. The library works on React Native without using rn-nodeify.

**Comment by lacvapps** [comment]
Awesome thank you
